---
- name: Apply sysctl settings.
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: "{{ sysctl_set }}"
    state: present
    reload: "{{ sysctl_reload }}"
  loop: "{{ sysctl_settings }}"
  when:
    - sysctl_settings is defined
    - item.name is defined
    - item.value is defined
